### ISSUE TITLE
VPC

### ISSUE THREAD

**Issue by golharam** [VCCRI/Falco#1]
Our organization requires our instances to run in a VPC.   How do I specify the VPC (or subnet id) to use?

**Comment by andr-kun** [comment]
Hi @golharam,

I have added optional configurations for the launch_cluster script which allows you to specify the VPC subnet ID (and security groups) for the EMR instances in the [latest commit](https://github.com/VCCRI/Falco/commit/6579e58bf0471f3c460e8d5982670725c6ab6d8d). I have also verified that the framework runs on VPC with a single public subnet configuration. Please try out the new launch_cluster script and feel free to get back to me if you encounter any issue.

Kind regards,
Andrian
